### ISSUE TITLE
unable to create an executable from build syntax

### ISSUE THREAD

**Issue by zferdana** [CoastalResilienceNetwork/geosite-framework-build#13]
building a region without specifying --dev or --prod should give an executable in the geosite-framework-build root directory. However, it calls for a login and password (e.g. build.py northcarolina-region) and does not build the executable. Is this an administration/permissions issue?

**Comment by mapossum** [comment]
I am noticing the same thing, but just for North Carolina.  NY builds just fine without --dev or --prod.  BTW specifying --dev or --prod still produces the executable (in the output directory), but also builds the site, so if you are ok building the site you can still get the executable.

**Comment by mmcfarland** [comment]
Looks like this is actually happening from the community_planning plugin repo

```
c:\projects\geosite-framework-build>python build.py northcarolina-region
Cloning northcarolina-region_config@HEAD...
Cloning GeositeFramework@HEAD...
Cloning GeositeFramework\src\GeositeFramework\plugins\flood_slr@HEAD...
Cloning GeositeFramework\src\GeositeFramework\plugins\restoration_explorer@HEAD...
Cloning GeositeFramework\src\GeositeFramework\plugins\community_planning@HEAD...
Username for 'https://github.com':
```

**Comment by mmcfarland** [comment]
This is due to a typo in the [plugin.json](https://github.com/CoastalResilienceNetwork/northcarolina-region/blob/master/plugins.json) for the northcarolina-region:

```json
        { 
            "repo": "community_planning",
            "name": "community_planning"
        }
```
should be

```json
        { 
          "repo": "community-planning",
           "name": "community_planning"
        }
```

Note the use of a dash instead of an underscore in the repo name.
