### ISSUE TITLE
Unable to run build due to MSBuild.exe error

### ISSUE THREAD

**Issue by erikmartin88** [CoastalResilienceNetwork/geosite-framework-build#18]
When a build is attempted there is an MSBuild.exe error stating that the proper version (v11.0) of Microsoft.WebApplication.targets is not found. (C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v11.0\WebApplications\Microsoft.WebApplication.targets).  There is a Microsoft.WebApplication.targets in a v14.0 folder (C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\WebApplications\Microsoft.WebApplication.targets), but renaming this as v11.0 introduces another suite of errors.

All other prerequisites are installed including Python, NSIS, and Git and the PATHs set.  MSBuild was installed via Visual Studio Community 2015.

![image](https://cloud.githubusercontent.com/assets/11949705/18286688/effb5a62-7441-11e6-985d-97792b2dc838.png)

**Comment by erikmartin88** [comment]
Microsoft.WebApplications.targets successfully copied to correct location, but new error now states "The project file could not be loaded, '>' is an unexpected token. The expected token is '='. Line 49, position 90. [c:\geosite-framework-build-locales\build\GeositeFramework\src\GeositeFramework\GeositeFramework.csproj]"

![image](https://cloud.githubusercontent.com/assets/11949705/18482406/fdb36b88-79ad-11e6-9cac-845314b1f69d.png)

**Comment by mmcfarland** [comment]
After downgrading to VS2012, the project builds for @erikmartin88, but ultimately fails due to missing Nuget package errors.

![image002](https://cloud.githubusercontent.com/assets/1014341/18639340/8c61c46c-7e61-11e6-83a2-47512ece3b97.jpg)

**Comment by mmcfarland** [comment]
This issue seems like it may be that NuGet is not configured to look for packages in the main repo.  Do you know if you have any other places that override the main configuration?  There might be a global config at `C:\Users\UserName\AppData\Roaming\NuGet\NuGet.config`

**Comment by erikmartin88** [comment]
Although the global config at  `C:\Users\UserName\AppData\Roaming\NuGet\NuGet.config` included the option to download nuget packages (`<add key="automatic" value="True" />`):

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <bindingRedirects>
    <add key="skip" value="False" />
  </bindingRedirects>
  <activePackageSource>
    <add key="NuGet official package source" value="https://nuget.org/api/v2/" />
  </activePackageSource>
</configuration>
```
Replacing the entire contents of this global config with the following empty configuration solved the problem.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration />
```

Thanks
