### ISSUE TITLE
geosite build: seflorida-region production

### ISSUE THREAD

**Issue by enlowe** [CoastalResilienceNetwork/geosite-framework-build#33]
SEFLorida failed to build after removing layer-selector plugins and adding regional planning plugins. I reverted my changes to previous commit and attempted to rebuild, resulting in the dialogue attached below:

`C:\geosite-framework-build-locales>build.py seflorida-region --prod
This will remove any current installation and install a new region website. Are
you sure you wish to continue? [y/n]: y
Cloning seflorida-region_config@HEAD...
Attempting to checkout the master branch
Your branch is up-to-date with 'origin/master'.
Cloning GeositeFramework@HEAD...
Attempting to checkout the master branch
Your branch is up-to-date with 'origin/master'.
Cloning GeositeFramework\src\GeositeFramework\plugins\coastal_defense@HEAD...
Attempting to checkout the master branch
Your branch is up-to-date with 'origin/master'.
Cloning GeositeFramework\src\GeositeFramework\plugins\floodSLR@HEAD...
Attempting to checkout the master branch
Your branch is up-to-date with 'origin/master'.
Cloning GeositeFramework\src\GeositeFramework\plugins\future_habitat@HEAD...
Attempting to checkout the master branch
Your branch is up-to-date with 'origin/master'.
Cloning GeositeFramework\src\GeositeFramework\plugins\riskexplorer@HEAD...
Attempting to checkout the master branch
Your branch is up-to-date with 'origin/master'.
Cloning GeositeFramework\src\GeositeFramework\plugins\layer_selector@HEAD...
Attempting to checkout the master branch
Branch master set up to track remote branch master from origin.
Cloning GeositeFramework\src\GeositeFramework\plugins\community_planning@HEAD...

Attempting to checkout the master branch
Branch master set up to track remote branch master from origin.
Copying region.json...
1 File(s) copied
Copying partners.html...
1 File(s) copied
Copying Proxy.config...
1 File(s) copied
Copying plugins...
24 File(s) copied
Copying img...
25 File(s) copied
Copying Views...
File not found - Views
0 File(s) copied
Copying methods...
12 File(s) copied
Copying sims...
File not found - sims
0 File(s) copied
Copying xml...
700 File(s) copied
Copying docs...
42 File(s) copied
Copying locales...
File not found - locales
0 File(s) copied
Microsoft (R) Build Engine version 4.0.30319.36366
[Microsoft .NET Framework, version 4.0.30319.36366]
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(983,5):
warning MSB3644: The reference assemblies for framework ".NETFramework,Version=
v4.0" were not found. To resolve this, install the SDK or Targeting Pack for th
is framework version or retarget your application to a version of the framework
 for which you have the SDK or Targeting Pack installed. Note that assemblies w
ill be resolved from the Global Assembly Cache (GAC) and will be used in place
of reference assemblies. Therefore your assembly may not be correctly targeted
for the framework you intend. [C:\geosite-framework-build-locales\build\Geosite
Framework\src\GeositeFramework\GeositeFramework.csproj]
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5):
 warning MSB3247: Found conflicts between different versions of the same depend
ent assembly. [C:\geosite-framework-build-locales\build\GeositeFramework\src\Ge
ositeFramework\GeositeFramework.csproj]
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5):
 warning MSB3270: There was a mismatch between the processor architecture of th
e project being built "MSIL" and the processor architecture of the reference "C
:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll", "x86". This mismatc
h may cause runtime failures. Please consider changing the targeted processor a
rchitecture of your project through the Configuration Manager so as to align th
e processor architectures between your project and references, or take a depend
ency on references with a processor architecture that matches the targeted proc
essor architecture of your project. [C:\geosite-framework-build-locales\build\G
eositeFramework\src\GeositeFramework\GeositeFramework.csproj]
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5):
 warning MSB3270: There was a mismatch between the processor architecture of th
e project being built "MSIL" and the processor architecture of the reference "S
ystem.Data", "AMD64". This mismatch may cause runtime failures. Please consider
 changing the targeted processor architecture of your project through the Confi
guration Manager so as to align the processor architectures between your projec
t and references, or take a dependency on references with a processor architect
ure that matches the targeted processor architecture of your project. [C:\geosi
te-framework-build-locales\build\GeositeFramework\src\GeositeFramework\GeositeF
ramework.csproj]
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5):
 warning MSB3270: There was a mismatch between the processor architecture of th
e project being built "MSIL" and the processor architecture of the reference "S
ystem.EnterpriseServices", "AMD64". This mismatch may cause runtime failures. P
lease consider changing the targeted processor architecture of your project thr
ough the Configuration Manager so as to align the processor architectures betwe
en your project and references, or take a dependency on references with a proce
ssor architecture that matches the targeted processor architecture of your proj
ect. [C:\geosite-framework-build-locales\build\GeositeFramework\src\GeositeFram
ework\GeositeFramework.csproj]
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5):
 warning MSB3270: There was a mismatch between the processor architecture of th
e project being built "MSIL" and the processor architecture of the reference "S
ystem.Web", "AMD64". This mismatch may cause runtime failures. Please consider
changing the targeted processor architecture of your project through the Config
uration Manager so as to align the processor architectures between your project
 and references, or take a dependency on references with a processor architectu
re that matches the targeted processor architecture of your project. [C:\geosit
e-framework-build-locales\build\GeositeFramework\src\GeositeFramework\GeositeFr
amework.csproj]
Creating installer executable...
Cloning installer\NSIS@HEAD...
3 File(s) copied
1 File(s) copied
Installing to production
Call to ['output\\tnc-ca-sefloridaSetup.exe', '/S', '/WEBSITE_NAME=Default Web S
ite', '/APP_URL=seflorida', '/REINSTALL_OVER=true', '/D=C:\\projects\\TNC\\seflo
rida'] failed

C:\geosite-framework-build-locales>`

**Comment by mmcfarland** [comment]
@enlowe Looks like the build tool built the installer successfully, but IIS rejected the new website.  Was IIS left in some intermediate state after the previous failure you reference in your issue?  IIS is notoriously difficult to get debug information out of.  Have you tried installing again?  Is `seflorida` currently listed in the IIS admin?

**Comment by enlowe** [comment]
SE Florida was listed in IIS. Uninstalled/removed the app and reinstalled with success
