### ISSUE TITLE
Update git clone usage to specify intended branch

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/geosite-framework-build#36]
Currently, cloning a repo in the TNC environment (framework, region or plugins) will fetch the default branch on the remote, which is `master`.  This has prevented us from switching to the `develop` branch as default for the rest of our development workflow, leading to mistakes or increased vigilance around target branches.  

Update the build tool to specify the appropriate branch, which likely will remain `master` when no other override options are present.

**Comment by caseycesari** [comment]
As part of this, we should clean-up usage of `--dev` and `--prod`, which are now somewhat obsolete since the tool doesn't install regions anymore. We may want to repurpose their usage in some way, or get rid of them.
